### `.streamlit/secrets.toml`
### Secret Management
### Open-Source, hosted on https://github.com/DrBenjamin/RAG-on-Snow
### Please reach out to ben@seriousbenentertainment.org for any questions
### App Setup
SNOWFLAKE = "true" 

### Snowflake Setup
# URL: https://sv04740.west-europe.azure.snowflakecomputing.com
[snowflake]
user = "bengross_tech"
account = "sv04740.west-europe.azure"
private_key_file = ".snowflake/rsa_key.p8"
role = "HEALTH_DEV"
warehouse = "WH_HEALTH_AI"
database = "DB_BG_HEALTH"
schema = "PUBLIC"
stage = "navigator"

### MinIO Setup
# URL: http://212.227.102.172:9001/login
[MinIO]
endpoint = "http://212.227.102.172:9000"
bucket = "templategenerator"
access_key = "health"
secret_key = "NOentry#23"
secure = "false"